[FilterPlugin]
; Includes
/Source/...
/Content/...
/Resources/...
/Config/...
/InstantOrganicCaves.uplugin
/Changelog.html
/Changelog.md

; Excludes
-/Intermediate/...
-/.git/...
-/.vs/...
-/Saved/...
